<?php $title = "Notes de l'élève" ?>

<?php ob_start() ?>
<h1>    

    <?= ucfirst(htmlspecialchars($notes[0]->getFirstname())) ?> 
    <?= ucfirst(htmlspecialchars($notes[0]->getLastname())) ?>

</h1>
    <ul>

    <?php foreach ($notes as $note) { ?>
    
    <li><?= $note->getSubject() ?> : <?= $note->getResult() ?></li>

    <?php } ?>
    
    </ul>

    <?php if ($appreciation) { ?>

    <fieldset>
        <legend>Commentaire</legend>
            <p><?= htmlspecialchars($appreciation->getComment()) ?></p>

        <?php if ($appreciation->getMention()) { ?>
            <p><strong><?= htmlspecialchars($appreciation->getMention()) ?></strong></p>
        <?php } ?>
            <a href="?route=edit&id=<?= $appreciation->getId() ?>">✏️</a>
            <a href="?route=delete&id=<?= $appreciation->getId() ?>&id_user=<?= $appreciation->getIdUser() ?>">❌</a>
    </fieldset>
    <?php } ?>

    <?php if (!$appreciation) { ?>

    <a href="?route=add&id=<?= $notes[0]->getIdUser() ?>">Remplir le bulletin</a><br><br>
    
    <?php } ?>
    
    <a href="?route=index">Retour à la classe</a>

<?php $content = ob_get_clean() ?>

<?php require 'src/view/base.phtml';
